language: python
python: 2.7
env:
  - TARGET=test CONFIG=buildout.cfg
#  - TARGET=python-validation.sh

install:
  - python bootstrap.py
  - bin/buildout -N -t 3 -c $CONFIG
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"
  - bzr whoami "Your Name <name@example.com>"
  - echo "[ui]">>~/.hgrc
  - echo "username = John Doe <john@example.com>">>~/.hgrc
       

script: bin/$TARGET 
